import openai
import re

openai.api_key = "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"

prompt = "The summary evaluation task refers to evaluate the summary based on the news article.\n" \
         "Your task is to list nineteen aspects that can be considered when measuring the relevance of summary.\n" \
         "Relevance: The rating measures how well the summary captures the key points of the article. " \
         "Consider whether all and only the important aspects are contained in the summary."

while True:
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "user",
                 "content": prompt},
            ],
            temperature=0,
            n=1
        )
        break
    except Exception as e:
        print(e)


content = response["choices"][0]["message"]["content"].split('\n')

aspects = {}
for c in content:
    if not c: continue
    c = c.split(":")
    aspects[re.sub(r'^[\d\s\W]+', '', c[0])] = c[1].strip()

print(aspects)

# {'Inclusion of key information': "One aspect to consider when measuring the relevance of a summary is whether it includes all the important aspects of the news article. This means that the summary should capture the main points, key details, and essential information from the article. It should not omit any crucial facts or events that are necessary for understanding the article's content.", 'Exclusion of irrelevant information': "Another aspect to consider is whether the summary excludes any irrelevant information from the news article. A relevant summary should focus on the essential aspects and avoid including unnecessary details, tangents, or unrelated information. It should provide a concise and focused overview of the article's main points without including any extraneous or non-essential content."}

# {'Inclusion of key information': 'A relevant summary should include all the important aspects and key points of the news article. It should cover the main ideas, events, and facts presented in the article without omitting any crucial details.', 'Exclusion of irrelevant information': 'A good summary should exclude any unnecessary or irrelevant information that does not contribute to the understanding of the main points of the article. It should focus on the most significant and relevant aspects, avoiding any tangential or unrelated details.', 'Comprehensiveness and coherence': 'The relevance of a summary also depends on its ability to provide a comprehensive and coherent overview of the article. It should present the main ideas and arguments in a logical and organized manner, ensuring that the summary is easy to understand and follow for readers.'}

# {'Coverage of key points': 'The summary should include all the important aspects and key points of the news article. It should cover the main ideas, events, and arguments presented in the article.', 'Accuracy of information': 'The summary should accurately represent the information and facts presented in the article. It should not misinterpret or distort the content of the article.', 'Conciseness and clarity': 'The summary should be concise and clear, presenting the information in a condensed and easily understandable manner. It should avoid unnecessary details and provide a clear overview of the article.', 'Coherence and coherence': 'The summary should be coherent and cohesive, presenting the information in a logical and organized manner. It should connect the different ideas and sections of the article, providing a cohesive summary of the main points.'}

{'Inclusion of key information': 'A relevant summary should include all the important aspects and key points of the news article. It should cover the main ideas, events, and facts presented in the article.',
 'Exclusion of irrelevant details': 'A good summary should exclude any unnecessary or irrelevant information that does not contribute to the understanding of the main points. It should focus on the most significant aspects of the article and avoid including minor details.',
 'Conciseness': 'A relevant summary should be concise and to the point. It should effectively condense the main ideas of the article into a shorter form without losing the essence of the information.',
 'Coherence': "The summary should present the information in a logical and coherent manner. It should connect the main points and ideas in a way that makes sense and provides a clear understanding of the article's content.",
 'Accuracy': 'A relevant summary should accurately represent the information presented in the article. It should not misinterpret or distort the facts, events, or ideas conveyed in the original text.'}

# {'Coverage of key points': 'The summary should include all the important aspects and key points of the news article. It should cover the main ideas, events, and arguments presented in the article.', 'Conciseness': 'A relevant summary should be concise and to the point. It should avoid unnecessary details and focus on the most significant information.', 'Coherence': 'The summary should present the information in a logical and coherent manner. It should connect the different ideas and events in a way that makes sense and provides a clear understanding of the article.', 'Accuracy': 'The summary should accurately represent the content of the news article. It should not misinterpret or distort the information presented in the article.', 'Importance of included aspects': 'The summary should prioritize the inclusion of the most important aspects of the article. It should focus on the key ideas, events, or arguments that are crucial for understanding the main message of the article.', 'Exclusion of irrelevant information': 'A relevant summary should exclude any irrelevant or tangential information that does not contribute to the understanding of the main points of the article. It should only include information that is directly related to the central theme or topic of the article.'}

# {'Coverage': 'Does the summary cover all the important aspects of the news article? It should include the main points, key details, and any significant developments or events mentioned in the article.', 'Conciseness': 'Is the summary concise and to the point? It should provide a brief overview of the article without unnecessary repetition or excessive details.', 'Accuracy': 'Does the summary accurately represent the information presented in the article? It should not misinterpret or distort the facts, quotes, or statements mentioned in the original news piece.', 'Coherence': 'Is the summary coherent and logically organized? It should present the information in a clear and structured manner, allowing readers to easily follow the main ideas and arguments presented in the article.', 'Objectivity': 'Does the summary maintain an objective tone? It should avoid personal opinions, biases, or subjective interpretations, focusing on presenting the facts and information objectively.', 'Importance': 'Does the summary highlight the most important aspects of the article? It should prioritize the key points and significant details, ensuring that readers get a comprehensive understanding of the news story.', 'Clarity': 'Is the summary written in a clear and understandable language? It should use simple and concise sentences, avoiding jargon or technical terms that may confuse or alienate readers.'}

# {'Coverage': 'Does the summary cover all the important aspects of the news article? It should include the main points, key details, and any significant developments or events mentioned in the article.', 'Conciseness': 'Is the summary concise and to the point? It should provide a brief overview of the article without unnecessary repetition or excessive details.', 'Accuracy': 'Does the summary accurately represent the information presented in the article? It should not misinterpret or distort the facts, quotes, or statements mentioned in the original news piece.', 'Coherence': 'Is the summary coherent and logically organized? It should present the information in a clear and structured manner, allowing readers to easily follow the main ideas and arguments.', 'Objectivity': 'Does the summary maintain an objective tone? It should avoid personal opinions, biases, or subjective interpretations, focusing on presenting the facts and information objectively.', 'Importance': "Does the summary highlight the most important aspects of the article? It should prioritize the key points and significant details, ensuring that readers grasp the essential information even if they don't read the full article.", 'Clarity': 'Is the summary written in a clear and understandable language? It should use simple and concise sentences, avoiding jargon or technical terms that may confuse or alienate readers.', 'Contextualization': "Does the summary provide enough context for readers to understand the article's significance? It should briefly explain the background, relevance, or implications of the news story, helping readers grasp its broader context."}

# {'Coverage': 'Does the summary cover all the main points and key details mentioned in the article?', 'Conciseness': 'Is the summary brief and to the point, without unnecessary repetition or excessive length?', 'Coherence': 'Does the summary present the information in a logical and organized manner, making it easy to understand?', 'Accuracy': 'Are the facts and information presented in the summary accurate and correctly represent the content of the article?', 'Objectivity': 'Does the summary provide a neutral and unbiased representation of the article, without adding personal opinions or biases?', 'Clarity': 'Is the summary written in clear and understandable language, avoiding jargon or complex terminology?', 'Importance': 'Does the summary focus on the most important aspects of the article, highlighting the key points that readers should know?', 'Context': "Does the summary provide enough context and background information to help readers understand the article's main points?", 'Readability': "Is the summary written in a way that is engaging and easy to read, capturing the reader's attention and maintaining their interest?"}

# {'Coverage of main points': 'The summary should include the main points and key information from the article.', 'Accuracy': 'The summary should accurately represent the content and context of the article.', 'Conciseness': 'The summary should be concise and avoid unnecessary details or repetition.', 'Coherence': 'The summary should present the information in a logical and coherent manner.', 'Objectivity': 'The summary should present the information objectively, without bias or personal opinions.', 'Clarity': 'The summary should be clear and easy to understand, avoiding jargon or complex language.', 'Contextualization': 'The summary should provide enough context to understand the main points of the article.', 'Focus': 'The summary should focus on the most important aspects of the article and avoid irrelevant details.', 'Completeness': 'The summary should cover all the important aspects of the article without omitting crucial information.', 'Readability': "The summary should be well-written and engaging, capturing the reader's attention."}

# {'Coverage': 'Does the summary cover all the main points and key details mentioned in the article?', 'Conciseness': 'Is the summary brief and to the point, without unnecessary repetition or excessive length?', 'Coherence': 'Does the summary present the information in a logical and organized manner, making it easy to understand?', 'Accuracy': 'Are the facts and information presented in the summary accurate and correctly represent the content of the article?', 'Objectivity': 'Does the summary present a balanced and unbiased view of the article, without adding personal opinions or biases?', 'Clarity': 'Is the summary written in clear and understandable language, avoiding jargon or technical terms that may confuse the reader?', 'Focus': 'Does the summary stay focused on the main topic and central theme of the article, without getting sidetracked or going off-topic?', 'Importance': 'Does the summary highlight the most important and relevant aspects of the article, giving them appropriate emphasis?', 'Completeness': 'Does the summary provide a comprehensive overview of the article, without leaving out any crucial information or details?', 'Readability': 'Is the summary written in a way that is easy to read and comprehend, using appropriate language and sentence structure?', 'Engagement': "Does the summary capture the reader's attention and interest, making them want to read the full article for more information?"}

# {'Coverage': 'Does the summary cover all the main points and key details mentioned in the article?', 'Conciseness': 'Is the summary brief and to the point, without unnecessary repetition or excessive length?', 'Clarity': 'Is the summary clear and easy to understand, conveying the main ideas of the article effectively?', 'Coherence': 'Does the summary present the information in a logical and organized manner, making it easy to follow?', 'Accuracy': 'Does the summary accurately represent the facts and information presented in the article, without distortion or misinterpretation?', 'Objectivity': 'Is the summary unbiased and objective, presenting the information without personal opinions or biases?', 'Importance': 'Does the summary focus on the most important aspects of the article, highlighting the key points and main ideas?', 'Context': "Does the summary provide enough context and background information to understand the article's subject matter?", 'Completeness': "Does the summary include all the necessary information to give a comprehensive overview of the article's content?", 'Relevance': "Is the summary relevant to the article's topic and subject matter, capturing the essence of the article accurately?", 'Language': 'Is the summary written in clear and concise language, using appropriate vocabulary and avoiding jargon or technical terms?', 'Engagement': "Does the summary engage the reader's interest and make them want to read the full article for more details?"}

# {'Coverage': 'Does the summary cover all the main points and important details mentioned in the article?', 'Conciseness': 'Is the summary brief and to the point, without unnecessary repetition or excessive length?', 'Clarity': 'Is the summary clear and easy to understand, without any ambiguity or confusion?', 'Coherence': 'Does the summary present the information in a logical and organized manner, making it easy to follow?', 'Accuracy': 'Does the summary accurately represent the facts and information presented in the article, without any distortions or misinterpretations?', 'Objectivity': 'Is the summary unbiased and objective, presenting the information without any personal opinions or biases?', 'Contextualization': 'Does the summary provide enough context and background information to understand the main points of the article?', 'Importance': 'Does the summary focus on the most important aspects of the article, highlighting the key points and main ideas?', 'Completeness': 'Does the summary provide a comprehensive overview of the article, without leaving out any crucial information?', 'Relevance': 'Does the summary focus on the most relevant aspects of the article, filtering out any irrelevant or tangential details?', 'Readability': 'Is the summary written in a clear and engaging manner, making it interesting and easy to read?', 'Language': 'Does the summary use appropriate language and terminology, avoiding jargon or technical terms that may be difficult for the general audience to understand?', 'Originality': 'Does the summary present the information in a unique and original way, adding value and providing a fresh perspective on the article?'}

# {'Coverage': 'Does the summary cover all the main points and key details mentioned in the article?', 'Conciseness': 'Is the summary brief and to the point, without unnecessary repetition or excessive length?', 'Clarity': 'Is the summary clear and easy to understand, conveying the main ideas of the article effectively?', 'Coherence': 'Does the summary present the information in a logical and organized manner, making it easy to follow?', 'Accuracy': 'Does the summary accurately represent the facts and information presented in the article?', 'Objectivity': 'Is the summary unbiased and objective, avoiding personal opinions or interpretations?', 'Completeness': 'Does the summary provide a comprehensive overview of the article, including all relevant aspects?', 'Focus': 'Does the summary maintain a clear focus on the main topic or subject of the article?', 'Importance': 'Does the summary prioritize the most important aspects of the article, giving them appropriate emphasis?', 'Contextualization': "Does the summary provide enough context and background information to understand the article's main points?", 'Language': 'Is the summary written in clear and concise language, avoiding jargon or technical terms that may confuse readers?', 'Readability': 'Is the summary written in a way that is easy to read and comprehend, using appropriate sentence structure and vocabulary?', 'Engagement': 'Does the summary engage the reader and generate interest in the article, making them want to read further?', 'Uniqueness': 'Does the summary offer a unique perspective or angle on the article, providing a fresh and original summary?'}

# {'Coverage of main ideas': 'Does the summary include the main ideas and key points of the article?', 'Inclusion of supporting details': 'Does the summary provide enough supporting details to understand the main ideas?', 'Accuracy of information': 'Does the summary accurately represent the information presented in the article?', 'Conciseness': 'Is the summary concise and to the point, avoiding unnecessary details?', 'Coherence and flow': 'Does the summary present the information in a logical and coherent manner?', 'Language and writing style': 'Is the summary written in clear and understandable language?', 'Objectivity': 'Does the summary present the information in an unbiased and objective manner?', 'Focus on important aspects': 'Does the summary prioritize the most important aspects of the article?', 'Exclusion of irrelevant information': 'Does the summary exclude any irrelevant or tangential information?', 'Clarity of main message': 'Does the summary clearly convey the main message or purpose of the article?', 'Use of quotes or citations': 'Does the summary appropriately use quotes or citations from the article?', 'Balance of perspectives': 'Does the summary provide a balanced representation of different perspectives presented in the article?', 'Contextualization': 'Does the summary provide enough context to understand the significance of the main ideas?', 'Engagement and interest': 'Does the summary engage the reader and generate interest in the article?', 'Length and format': 'Does the summary adhere to the required length and format guidelines?'}

# {'Coverage': 'Does the summary cover all the important aspects of the news article?', 'Accuracy': 'Is the information in the summary accurate and correctly represented from the article?', 'Completeness': 'Does the summary include all the necessary details and context from the article?', 'Conciseness': 'Is the summary brief and to the point, without unnecessary repetition or wordiness?', 'Clarity': 'Is the summary written in a clear and understandable manner, avoiding jargon or complex language?', 'Objectivity': 'Does the summary avoid personal opinions or biases?', 'Coherence': 'Does the summary present the information in a logical and coherent order?', 'Focus': 'Does the summary maintain a clear focus on the main points of the article?', 'Relevance': 'Does the summary include only the information that is relevant to the main topic of the article?', 'Tone': 'Does the summary reflect the tone and style of the original article?', 'Structure': 'Does the summary follow a well-organized structure, such as an introduction, body, and conclusion?', 'Language': 'Is the summary written in appropriate and professional language?', 'Readability': 'Is the summary easy to read and understand for the target audience?', 'Balance': 'Does the summary provide a balanced representation of different perspectives or sides of the story?', 'Engagement': 'Does the summary engage the reader and make them interested in reading the full article?'}

# {'Coverage': 'Does the summary cover all the main points and key details mentioned in the article?', 'Conciseness': 'Is the summary brief and to the point, without unnecessary repetition or excessive length?', 'Clarity': 'Is the summary clear and easy to understand, conveying the main ideas of the article effectively?', 'Coherence': 'Does the summary present the information in a logical and organized manner, making it easy to follow?', 'Accuracy': 'Does the summary accurately represent the facts and information presented in the article?', 'Objectivity': 'Does the summary present a balanced view of the article, avoiding any bias or subjective opinions?', 'Completeness': 'Does the summary provide a comprehensive overview of the article, including all relevant aspects?', 'Focus': 'Does the summary maintain a clear focus on the main topic or subject of the article?', 'Importance': 'Does the summary prioritize the most important aspects of the article, giving them appropriate emphasis?', 'Contextualization': "Does the summary provide enough context and background information to understand the article's main points?", 'Language': 'Is the summary written in clear and concise language, avoiding jargon or technical terms that may confuse readers?', 'Readability': 'Is the summary written in a way that is easy to read and comprehend, considering the target audience?', 'Structure': 'Does the summary have a clear and logical structure, with an introduction, body, and conclusion?', 'Relevance': 'Does the summary focus on the most relevant aspects of the article, avoiding unnecessary details or tangents?', 'Engagement': 'Does the summary engage the reader and make them interested in reading the full article?', 'Originality': "Does the summary present the information in a unique and original way, adding value beyond simply restating the article's content?"}

# {'Main topic': 'Does the summary accurately convey the main topic or subject matter of the article?', 'Key points': 'Does the summary include the most important points or arguments made in the article?', 'Scope': 'Does the summary cover the entire article or only a specific section or aspect?', 'Accuracy': 'Does the summary accurately represent the information and facts presented in the article?', 'Completeness': 'Does the summary provide a comprehensive overview of the article or is it missing important details?', 'Conciseness': 'Is the summary concise and to the point, avoiding unnecessary repetition or excessive length?', 'Clarity': 'Is the summary written in a clear and understandable manner, avoiding jargon or complex language?', 'Objectivity': 'Does the summary present the information in an unbiased and objective manner, without personal opinions or biases?', 'Tone': 'Does the summary reflect the tone and style of the original article, whether it is formal, informal, persuasive, etc.?', 'Structure': 'Does the summary follow a specific structure, such as a chronological order, cause-effect relationship, or problem-solution format?', 'Coherence': 'Are the sentences and paragraphs in the summary connected and flow smoothly, allowing for easy comprehension?', 'Language': 'Is the summary written in appropriate and grammatically correct language, without spelling or grammatical errors?', 'Importance': 'Does the summary highlight the most important aspects of the article, distinguishing them from less significant details?', 'Objectives': 'Does the summary align with the objectives or purpose of the article, whether it is to inform, persuade, entertain, etc.?', 'Context': "Does the summary provide enough context or background information for readers to understand the article's content?", 'Significance': "Does the summary emphasize the significance or implications of the article's findings or arguments?", 'Engagement': "Does the summary engage the reader's interest and make them want to read the full article for more information?"}

# {'Accuracy': 'Does the summary accurately represent the information and facts presented in the article?', 'Completeness': 'Does the summary cover all the important aspects and key points of the article?', 'Conciseness': 'Is the summary brief and to the point, without unnecessary details or repetition?', 'Coherence': 'Does the summary present the information in a logical and organized manner?', 'Objectivity': 'Does the summary avoid personal biases or opinions, presenting the information objectively?', 'Clarity': 'Is the summary clear and easy to understand, without ambiguity or confusion?', 'Focus': 'Does the summary stay focused on the main topic and avoid irrelevant information?', 'Structure': 'Does the summary have a clear introduction, body, and conclusion?', 'Tone': 'Does the summary match the tone and style of the original article?', 'Language': 'Is the summary written in clear and concise language, without jargon or technical terms?', 'Contextualization': "Does the summary provide enough context for readers to understand the article's significance?", 'Emphasis': 'Does the summary highlight the most important aspects and key points of the article?', 'Organization': 'Is the summary well-structured, with a logical flow of information?', 'Relevance': 'Does the summary focus on the most relevant and significant aspects of the article?', 'Originality': "Does the summary present the information in a unique and creative way, without simply restating the article's content?", 'Engagement': "Does the summary capture the reader's attention and make them want to read the full article?", 'Timeliness': 'Does the summary provide up-to-date information and reflect the current state of affairs?'}

# {'Accuracy': 'Does the summary accurately represent the information and facts presented in the article?', 'Completeness': 'Does the summary cover all the important aspects and key points of the article?', 'Conciseness': 'Is the summary brief and to the point, without unnecessary details or repetition?', 'Coherence': 'Does the summary present the information in a logical and organized manner?', 'Objectivity': 'Does the summary avoid personal biases or opinions, presenting the information objectively?', 'Clarity': 'Is the summary clear and easy to understand, without ambiguity or confusion?', 'Focus': 'Does the summary stay focused on the main topic and central ideas of the article?', 'Structure': 'Does the summary follow a logical structure, such as chronological order or cause-effect relationships?', 'Tone': 'Does the summary match the tone and style of the original article?', 'Language': 'Is the summary written in clear and concise language, without jargon or technical terms?', 'Importance': 'Does the summary highlight the most important aspects and key takeaways of the article?', 'Context': 'Does the summary provide enough context and background information for the reader to understand the article?', 'Relevance': 'Does the summary address the main issues and topics discussed in the article?', 'Balance': 'Does the summary present a balanced view of the article, considering different perspectives if applicable?', 'Significance': "Does the summary capture the significance and implications of the article's findings or events?", 'Timeliness': 'Does the summary reflect the most recent and up-to-date information from the article?', 'Originality': 'Does the summary present the information in a unique and original way, avoiding plagiarism?', 'Engagement': 'Does the summary engage the reader and make them interested in reading the full article?'}
